version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: fontes-nodejs
    container_name: fontes-nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - BASE_URL=$BASE_URL
    ports:
      - "7500:20561"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ash -c "
        ./styles.sh '$BASE_URL' &&
        ./scripts.sh '$BASE_URL' &&
        pm2-runtime npm  -- start
      "
    depends_on: [db]

  db:
    image: mongo:4.2
    container_name: fontes-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: